author: eccentric_nz
description: Chunk generator for the TARDIS plugin
main: me.eccentric_nz.tardischunkgenerator.TARDISHelper
name: TARDISChunkGenerator
load: STARTUP
url: http://dev.bukkit.org/bukkit-plugins/tardis/
version: 4.12.1
api-version: 1.19
